// <auto-generated />
using System;
using BrainHub.DomainLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrainHub.DomainLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrainHub.DomainLayer.Models.CustomRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Permissions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Employee Manager",
                            Permissions = "EmployeeIndex,EmployeeAdd,EmployeeUpdate,EmployeeDelete"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sbu Manager",
                            Permissions = "SbuIndex,SbuAdd,SbuUpdate,SbuDelete"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CustomRole Manager",
                            Permissions = "CustomRoleIndex,CustomRoleAdd,CustomRoleUpdate,CustomRoleDelete"
                        });
                });

            modelBuilder.Entity("BrainHub.DomainLayer.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomRoleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SbuId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomRoleId");

                    b.HasIndex("SbuId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Number = "01111111111",
                            SbuId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "John Doe",
                            Number = "01710000001",
                            SbuId = 2,
                            UserId = 101
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jane Smith",
                            Number = "01710000002",
                            SbuId = 3,
                            UserId = 102
                        },
                        new
                        {
                            Id = 4,
                            Name = "Michael Johnson",
                            Number = "01710000003",
                            SbuId = 4,
                            UserId = 103
                        },
                        new
                        {
                            Id = 5,
                            Name = "Emily Davis",
                            Number = "01710000004",
                            SbuId = 2,
                            UserId = 104
                        },
                        new
                        {
                            Id = 6,
                            Name = "Daniel Brown",
                            Number = "01710000005",
                            SbuId = 3,
                            UserId = 105
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sophia Wilson",
                            Number = "01710000006",
                            SbuId = 4,
                            UserId = 106
                        },
                        new
                        {
                            Id = 8,
                            Name = "David Miller",
                            Number = "01710000007",
                            SbuId = 2,
                            UserId = 107
                        },
                        new
                        {
                            Id = 9,
                            Name = "Olivia Anderson",
                            Number = "01710000008",
                            SbuId = 3,
                            UserId = 108
                        },
                        new
                        {
                            Id = 10,
                            Name = "James Thomas",
                            Number = "01710000009",
                            SbuId = 4,
                            UserId = 109
                        },
                        new
                        {
                            Id = 11,
                            Name = "Isabella Martinez",
                            Number = "01710000010",
                            SbuId = 2,
                            UserId = 110
                        },
                        new
                        {
                            Id = 12,
                            Name = "a",
                            Number = "01710000011",
                            SbuId = 2,
                            UserId = 111
                        });
                });

            modelBuilder.Entity("BrainHub.DomainLayer.Models.Sbu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sbus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "HR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a078065-9b31-49c2-8660-c86bdf6f9242",
                            Email = "admin@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BRAINHUB.COM",
                            NormalizedUserName = "ADMIN@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGnCQmiIP+R6QGj0ylUaZf0dODZvPh9ViXXMrXc9mOrklht+8GS2SXY1++6ajcMqhA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "410988e0-b88e-474d-867f-3e073045e11a",
                            TwoFactorEnabled = false,
                            UserName = "admin@brainhub.com"
                        },
                        new
                        {
                            Id = 101,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4f6ba237-5c7d-4bfd-9ecf-462eb5f7aaf8",
                            Email = "johndoe@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOHNDOE@BRAINHUB.COM",
                            NormalizedUserName = "JOHNDOE@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKvW2Dw6F8cKoRfSb8PDgEVCsGDGJABfUtke9nnZakSDqkkWrc72AaRngkDCxxfpbg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9c4ac73-8ad4-47f0-a88c-15a837333a39",
                            TwoFactorEnabled = false,
                            UserName = "johndoe@brainhub.com"
                        },
                        new
                        {
                            Id = 102,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ad1ca2f4-7771-451f-81e8-27d1ed256d26",
                            Email = "janesmith@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JANESMITH@BRAINHUB.COM",
                            NormalizedUserName = "JANESMITH@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0YYl+6Av6msNX4XtjWeNd/vFnyOc05SY1VymZ5a17REfjFg5a7A9Gcdi8RdhqxaQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5ce0cefc-e06b-4ffa-8e52-a2b667952334",
                            TwoFactorEnabled = false,
                            UserName = "janesmith@brainhub.com"
                        },
                        new
                        {
                            Id = 103,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "20878ced-8824-4edf-88f6-76d19075bcde",
                            Email = "michaeljohnson@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "MICHAELJOHNSON@BRAINHUB.COM",
                            NormalizedUserName = "MICHAELJOHNSON@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENuMsXQbVGasgQhbBWu+aMY4dJCbRbj2txTe2Hdv/sK+wDFgPLu99kSw24dk6hQf7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bda3965a-5419-4054-a32d-152d65fcd2e0",
                            TwoFactorEnabled = false,
                            UserName = "michaeljohnson@brainhub.com"
                        },
                        new
                        {
                            Id = 104,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dbe792d1-ffe4-431e-aea4-56c7fd94ccbe",
                            Email = "emilydavis@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMILYDAVIS@BRAINHUB.COM",
                            NormalizedUserName = "EMILYDAVIS@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIP3uk9JHRhfUMxXcgXYhCYTfe//+6FOlYSZ4jrjvnj9f5DNcXyktLule6JzWZeV3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31bd2582-4caa-44af-a73d-edd4db5f7949",
                            TwoFactorEnabled = false,
                            UserName = "emilydavis@brainhub.com"
                        },
                        new
                        {
                            Id = 105,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96bbc135-8552-4782-b2d6-0b4029fd6c77",
                            Email = "danielbrown@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DANIELBROWN@BRAINHUB.COM",
                            NormalizedUserName = "DANIELBROWN@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM2mVgcjGgCkRWJh5QWnR/Xp/2SgoLCENlNgl35GaDk8LmpTmr+xl6S6j10P0w8ZMA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "52054539-d30a-43be-b50e-b648842816f2",
                            TwoFactorEnabled = false,
                            UserName = "danielbrown@brainhub.com"
                        },
                        new
                        {
                            Id = 106,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ba39099-73bf-4663-b67e-1c1a7b0ae61f",
                            Email = "sophiawilson@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SOPHIAWILSON@BRAINHUB.COM",
                            NormalizedUserName = "SOPHIAWILSON@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJLvSf+26WfbO60S5CR7OhU4KYVo0WDVyHma1sQNNN29UJgaJRkfgPI+UcspBdZArg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "28edf3bf-d46c-4eee-aac1-8b55fed79ed3",
                            TwoFactorEnabled = false,
                            UserName = "sophiawilson@brainhub.com"
                        },
                        new
                        {
                            Id = 107,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba1f1de2-7d29-47b0-8108-4ad0d948635d",
                            Email = "davidmiller@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DAVIDMILLER@BRAINHUB.COM",
                            NormalizedUserName = "DAVIDMILLER@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJyoGKOqZ956rwoIWknL3Q6E81i9RWwkvFlxjwvQ7hfF6w0lNo5i+YX2koUJTlmk7w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c804196-265c-44e3-ad84-f706c7ade16b",
                            TwoFactorEnabled = false,
                            UserName = "davidmiller@brainhub.com"
                        },
                        new
                        {
                            Id = 108,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af8dd45e-3f81-4829-8e68-6866485f0da6",
                            Email = "oliviaanderson@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "OLIVIAANDERSON@BRAINHUB.COM",
                            NormalizedUserName = "OLIVIAANDERSON@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEO6lETU2IZp7PCAEBVKfBEhtCyiiCVMQeS724uvlUNsRmRvm88FhUiY/1HUO1BMLkA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9109f8a-d2fa-431a-8716-cd14c3e389d2",
                            TwoFactorEnabled = false,
                            UserName = "oliviaanderson@brainhub.com"
                        },
                        new
                        {
                            Id = 109,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2f9889f-1839-4339-8494-975d25168d56",
                            Email = "jamesthomas@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JAMESTHOMAS@BRAINHUB.COM",
                            NormalizedUserName = "JAMESTHOMAS@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJdHBp6HaBsb/Ve2mLbTSZJV2JnKjUwAOi3FgE1bmdglGf6PVKhMW5T5mdo7UZKv7Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a1cc781-8fe2-4a72-8a7f-6c06416f719c",
                            TwoFactorEnabled = false,
                            UserName = "jamesthomas@brainhub.com"
                        },
                        new
                        {
                            Id = 110,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a29c572b-19cb-4cc4-b172-7774249c67a5",
                            Email = "isabellamartinez@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ISABELLAMARTINEZ@BRAINHUB.COM",
                            NormalizedUserName = "ISABELLAMARTINEZ@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAlDQoieu1r/qi+l719mvYrPxbtGzWKYxcjrnWnO9gg5Gt7BEhML0YVsb8hERz2hPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1e9556a5-7e1b-49ae-be81-4b1779edd209",
                            TwoFactorEnabled = false,
                            UserName = "isabellamartinez@brainhub.com"
                        },
                        new
                        {
                            Id = 111,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cf38bfec-24be-4266-a761-6510e527d70c",
                            Email = "a@brainhub.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "A@BRAINHUB.COM",
                            NormalizedUserName = "A@BRAINHUB.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEA6pMwQrsSyj71OmT4WuHSOavFP/tEM422BWhMWEGSEpggqMEn0gAh5OMQ989f1JA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3a82cb04-5903-4244-bf3f-923165cde0ae",
                            TwoFactorEnabled = false,
                            UserName = "a@brainhub.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 101,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 102,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 103,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 104,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 105,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 106,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 107,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 108,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 109,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 110,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 111,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BrainHub.DomainLayer.Models.Employee", b =>
                {
                    b.HasOne("BrainHub.DomainLayer.Models.CustomRole", "CustomRole")
                        .WithMany()
                        .HasForeignKey("CustomRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BrainHub.DomainLayer.Models.Sbu", "Sbu")
                        .WithMany()
                        .HasForeignKey("SbuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", "User")
                        .WithOne()
                        .HasForeignKey("BrainHub.DomainLayer.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CustomRole");

                    b.Navigation("Sbu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser<int>", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
